name: Merge Release Into Main

on:
  push:
    branches:
      - 'dev/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"

      - name: Auto approve
        id: auto-approve
        if: steps.open-pr.outputs.pr_number != ''
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          number: ${{ steps.open-pr.outputs.pr_number }}
        continue-on-error: true

      - name: Check approval result
        if: always()
        run: |
          if [ "${{ steps.open-pr.outputs.pr_number.outcome }}" == "success" ]; then
            echo "✅ PR approved successfully!"
          else
            echo "❌ Failed to auto approve the PR"
            exit 1
          fi
  

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: Enable Automerge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: squash

      - name: Check Automerge Result
        run: |
          if [ "${{ steps.open-pr.outputs.pr_number.outcome }}" == "success" ]; then
            echo "✅ Auto-merge enabled successfully!"
          else
            echo "❌ Failed to enable auto-merge on PR"
            exit 1
          fi
        
      - name: Delete source branch
        if: steps.open-pr.outputs.pr_number.outcome == 'success'
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "🔄 Deleting branch: $BRANCH_NAME"
      
          gh auth login --with-token <<< "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          gh api \
            -X DELETE \
            "repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
      
          echo "✅ Branch '$BRANCH_NAME' deleted."
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
